### ISSUE TITLE
Configure LayoutWizzard for Wellcome use cases

### ISSUE THREAD

**Issue by opaetzel** [wellcomecollection/goobi-infrastructure#286]
After the LayoutWizzard is available in AWS, we have to configure it for the material we want to process.

**Comment by aray-wellcome** [comment]
@opaetzel Here are the specifications for cropping laid out by our photographer Laurie for LayoutWizzard testing. 
[Layout Wizard Test Guide.docx](https://github.com/wellcomecollection/goobi-infrastructure/files/4473768/Layout.Wizard.Test.Guide.docx)

**Comment by aray-wellcome** [comment]
@opaetzel We have feed back from the photographers from their latest testing. It seems they are most likely moving ahead with LW but have some adjustments they need made. We will also need an approximation of the amount of work and the cost for the adjustments.  

**1. Making LayoutWizzard work in the Cloud**
How much work is necessary to make this possible and what would the project quote be?

**2. Make the bounding box more precise**
Currently the blue bounding box is placed on the paper pages and misses the edge of the covers. The photographers are hoping that the edges of the book can be captured better through analysis so they don't have to adjust as much

**3. Filtering**
The photographers want to explore more accurate filtering around the book. For the most part the current set up works but leaves slices of unfiltered background near the book when it's not perfectly straight. Is there a way to improve on this that we haven't thought of? Or do we need to consider the threshold approach? What are the pros/cons of the threshold? If the threshold method isn't likely to work as well as wanted, the filtering and cleanup may be dropped as a requirement but they want to explore options first. 

**4. Image changes**
The photographers are interested in having additional steps in the LW workflow that allows them to QA the images and send images back for individual fixing if needed. I know there are some steps that probably already exist that we can use but I'm not sure what they are. 

**5. Detailed images**
This is more of a clarification. If they have shot a detail page and want the entire image to appear as-is, can they just expand the bounding box to the edges of the image? There was a pixel out-of-bounds error that had occurred before and they weren't sure if using the bounding box at the edge of the image wouldn't cause it to happen again.

**Comment by opaetzel** [comment]
**1. Making LayoutWizzard work in the Cloud**
I would estimate 3 weeks of work to make the LayoutWizzard work in the cloud with autoscaling 

**2. Make the bounding box more precise**
We could move the border further to the outside with an automatically added margin or maybe tweak the configuration to get the covers into the bounding box. Could you give us Goobi process IDs where the bounding box recognition was unprecise?

**3. Filtering**
I think the flood-fill with a manually set threshold is the best variant we could use. The pros of this method would be that we would have more accurate filtering around the book. The are that we will need more human interaction and more time would be needed to finish a book as there would be an additional step to do.  
Implementing this together with a new interface that allows to set the threshold effectively for multiple images would take about 2 weeks. 

**4. Image changes**
The QA can be done in the imageQA plugin and then the workflow can be sent back to the previous step with a correction message. There, the images can be replaced by re-uploading them. See the Goobi workflow documentation here for details: https://docs.goobi.io/goobi-workflow-en/user/3/3.2

**5. Detailed images**
This is probably a bug in the filtering step in the LayoutWizzard. Moving the bounding box to the edge of the images should work fine in this case. I will have a look and fix the error.

**Comment by aray-wellcome** [comment]
**Re: 1 Cloud LW**

That doesn't sound as bad as I thought it'd be!

**Re: 2 Bounding Box**

I think b19364994 might be a good example of that. It's completed now but [you can see that the edge of the book covers](http://universalviewer.io/uv.html?manifest=https://dlcs.io/iiif-resource/wellcome/item/b19364994#?c=0&m=0&s=0&cv=17&xywh=-3362%2C0%2C10755%2C5085) are dark and the pages are pretty bright comparatively. The bounding box probably went around the edge of the bright page rather than include the darker book cover edge background. The photographers said there was a lot of manual adjusting to include the covers within the bounding box that they'd like eliminated as much as possible. 

**Re: 3 Filtering**

I might have to bring this back to the photography team. They seem to expect LW to have minimal human interaction so adding an additional step to improve the filtering might be unappealing, especially if they're willing to remain with the current filtering or eliminate it altogether. 

**Re 4: Image Changes**

This sounds about what they wanted, I think. Would we be able to have this in staging to look at if it's not too much work to add? 


**Re: 5 Detailed Images**

Ok, thanks for having a look! Florian helped solve the pixel out of bounds error but we weren't sure what caused it. You can find it on Slack here https://wellcome.slack.com/archives/C6LLC2V8Q/p1596536475013600

**Comment by aray-wellcome** [comment]
Just to officially keep track of decisions on here, the photographers want to test the threshold filtering themselves in the LW plugin.

**Comment by aray-wellcome** [comment]
Closing as work is mainly done and LW is being put into the cloud in #340 . Reopen another ticket if tweaks needed by photographers.
