### ISSUE TITLE
EP: Unexpected CSV content fails silently with NullpointerException

### ISSUE THREAD

**Issue by opaetzel** [wellcomecollection/goobi-infrastructure#349]
This is not ideal, as the user will never know what went wrong.

**Comment by aray-wellcome** [comment]
Based on this chat https://wellcome.slack.com/archives/C6LLC2V8Q/p1633524890238100 I think we fixed this? It doesn't have a UI but it moves to the failed folder, right? I actually got this tested this week, a malformed shoot csv came through and went to failed instead of just disappearing and never showing up in Goobi. So I think that was all we wanted on this and we can close?

**Comment by opaetzel** [comment]
Yes, I guess that we can close this now.
