### ISSUE TITLE
RFC: SQS/worker node monitoring outside of ITM

### ISSUE THREAD

**Issue by aray-wellcome** [wellcomecollection/goobi-infrastructure#354]
As the following jobs are moving to the SQS/worker node, it is understood that they will no longer be able to be tracked on the Intranda Task Manager as it will just be one large queue:

- Lurawave 
- JPEG conversion
- IA-Parser
- ALTO-convert
- BagIt
- jpylyzer

Lurawave, JPEG conversion, and Bagit are plugins I use especially to monitor how many items are going through Goobi and how fast they are moving. Items often spend the longest times in JPEG conversion and Bagit and these are the plugins most likely to need attention. 

I was asked to think about how I use the ITM and if there was a solution we could put into Goobi. My initial thoughts:

1. I like to know how many items are at each step
2. Need a way to track errors happening in real time and recent past
3. I also use the timestamps a lot for many reasons
4. I do see if something is particularly large is holding something up
5. I do cancel things to shuffle priority if I need to
6. It would be good to prioritize things on occasion through the queues

**Proposed idea for tracking progress and errors**
I have some thoughts on how I could track items inside of Goobi, for all plugins, not just the ones above. It basically comes down to using the time stamps on the step statuses, which is something that would hopefully be easy to expose and search on in different places. 

1. Updating the plugin dashboard to include items in progress and recent errors for each step
![image](https://user-images.githubusercontent.com/49983203/104293560-0899a480-54b6-11eb-8c6b-7d999911f165.png)

It's probably not possible to specifically say which process is currently being put through a plugin due to the new queue system but if we could do it, that'd be great. I'd mostly like to know because it's nice for me to see if a certain item is holding things up--sometimes it's large so I give it a while or sometimes it doesn't make sense why it's taking so long and I check with you guys. 

It'd be good to have a number of how many processes were at each step without having to search. If the number could be displayed and then made clickable so I could see the full list of items, that'd be ideal

Lastly, errors are very hard to keep track of outside of the ITM. It'd be good to have a number of how many errors are at that plugin step within say, the last 7 days. These should be fairly current issues that would be taken care of ASAP. 

2. Expose timestamps for step statuses in search results
![image](https://user-images.githubusercontent.com/49983203/104295940-fa00bc80-54b8-11eb-9b11-4e8884fe8106.png)

Currently if I go looking for stuck items or errors, I have to open them and hover over the colored box to see the last update on the step. It would be good to have the last timestamp for a step status exposed so I can quickly find newer processes that are having issues without having to open each one. 

Furthermore, the process date we can expose doesn't help as it is the day that the metadata was loaded in for an item and we usually do that in bulk and well in advance. 

3. Allow timestamps to be searched on
![image](https://user-images.githubusercontent.com/49983203/104296109-2c121e80-54b9-11eb-9407-4ea6f1fe3ec1.png)

If I have a known day, for example, that there was an ingest I would like to be able to search for "stepcompleted:Image Upload 7-1-2021" for example so I can have a look at all the items ingested that day and see if there are any issues or how many went through. 

**Prioritizing**
The ITM has some mechanism for prioritizing items through the queue but I have never been able to get it to work. I'm not sure how prioritizing outside of the ITM would work in the SQS/worker node. Are there any ideas on this from Intranda?

**Comment by rsehr** [comment]
My thoughts on the search for dates or timestamps

Different relevant dates

* process creation date
* step editing start date
* step editing finish date

Different date formats for languages/countries:

* 01.06.2020 or 1.6.2020 in Germany
* 01-06-2020 or 1-6-2020 in UK
* 6/1/2020 in USA
* ...

Different granularity of dates:

* 2020
* 2020-01-01
* 2020-01-01 00:00:00

Different search parameter for dates:

* date is equal to the searchvalue
* date is sooner than the searchvalue
* date is after than thesearchvalue
* date is not equal to the searchvalue

Proposed solution: 
only w3cdtf / iso8601 formats are allowed. The format defines dates like this:
YYYY
YYYY-MM-DD
YYYY-MM-DDThh:mm:ssZ
For a better understanding, I would make T and Z optional, so we would allow the fourth option 
YYYY-MM-DD hh:mm:ss

If a user uses the exact date including time, the exact date is used, otherwise the date field is filled automatically based on the search parameter.

If the parameter equal or not equal are used, the date 2020-01-01 will search for dates between 2020-01-01 00:00:00 and 2020-01-01 23:59:59. A year only will get extendend to 2020-01-01T00:00:00Z and 2020-12-31T23:59:59Z.

When a date must be smaller than an incomplete search value, the missing date fields are filled with the highest possible value. Missing time is set to 23:59:59 and the date to 12-31. On searches for dates greater than the search value, the missing date fields are filled with the earliest possible value. The time is set to 00:00:00 and the day and month to 01-01.
