### ISSUE TITLE
Run bagit creation on ec2 instance with attached EBS

### ISSUE THREAD

**Issue by opaetzel** [wellcomecollection/goobi-infrastructure#426]
To handle bigger MXF movies, the bagit creation shall be run on an ec2 instance with an attached EBS. To do this, the following needs to be done:

- [x] Goobi has to write the bagit jobs to a different queue (will be done in a new step plugin)
- [ ] create a new SQS queue in terraform
- [ ] add ENV variables for the new queue to goobi
- [ ] We need to create a new ECS cluster based on  an EC2 instance with EBS attached
- [ ] create worker node task on new EC2 based cluster (configured to check the newly created queue)

**Comment by alexwlchan** [comment]
Do you have autoscaling enabled for your tasks?

If so, you might be able to copy a pattern we have elsewhere in the pipeline. We have an autoscaling group of EC2 instances that act as an ECS capacity provider, and which scale based on the tasks required. The task is a standard ECS task (you change the launch type from "Fargate" to "EC2" and define some volume mounts).

This gets you nice autoscaling-y benefits, and means you can provision the EC2 instance to be faster/more powerful because it'll autoscale away when not in use.

These are where the EC2 capacity provider/ECS task are defined where we do this, to give you a flavour:

https://github.com/wellcomecollection/catalogue-pipeline/blob/main/pipeline/terraform/stack/cluster.tf#L6-L27
https://github.com/wellcomecollection/catalogue-pipeline/blob/main/pipeline/terraform/stack/service_image_inferrer.tf

**Comment by mgeerdsen** [comment]
Thanks a lot for the hint @alexwlchan , as the service is using autoscaling we used this setup in [branch bagit_on_ec2-ebs](/wellcomecollection/goobi-infrastructure/tree/bagit_on_ec2-ebs) for testing/experimenting so far.

What we actually need is an ECS service with mounted storage from an attached EBS volume. (EC2 hosted service is added [here](https://github.com/wellcomecollection/goobi-infrastructure/blob/bagit_on_ec2-ebs/infrastructure/staging/main.tf#L305) with [this module](https://github.com/wellcomecollection/goobi-infrastructure/blob/bagit_on_ec2-ebs/infrastructure/modules/stack/worker_node/main.tf) being used.)

However the storage size inside the container still appears to be the one of the root volume (roughly 30 GB). Did I overlook something here and is the desired currently even possibile with the ec2_capacity_provider module you mentioned or would it have to be tweaked with a different config for the EC2 instance? I fear I got too confused with the storage setup in the end.
